# Generated by Django 3.0.1 on 2020-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_edition_image_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={},
        ),
        migrations.AddField(
            model_name='edition',
            name='rules_url',
            field=models.URLField(blank=True, null=True, verbose_name='rules url'),
        ),
        migrations.AddField(
            model_name='edition',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='harbormaster',
            field=models.BooleanField(default=False, verbose_name='harbormaster VP'),
        ),
    ]
