# Generated by Django 3.0.1 on 2020-01-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20200105_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ('game_type',)},
        ),
    ]
