# Generated by Django 3.0.1 on 2020-01-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20200112_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue'), ('WH', 'White'), ('OR', 'Orange'), ('GR', 'Green'), ('BR', 'Brown'), ('PK', 'Pink'), ('YL', 'Yellow')], default='RD', max_length=2, verbose_name="player's color"),
        ),
    ]
